db["Animals"].find({ "type" : "Bird" })
db["Animals"].find({ "found_in_countries" : "Australia" })
db["Animals"].find({ "conservation_status": "Critically Endangered" })
db["Animals"].find({$and: [{ "diet": "Herbivore" }, { "habitat": "Forest"}]})
db["Animals"].find({ "physical_characteristics.weight": { "$gt": 500000 } })
db["Animals"].find({ "physical_characteristics.height": { "$lt": 100 } })
db["Animals"].find({ "found_in_countries": "China" })
db["Animals"].find({$and: [{ "diet": "Omnivore" }, { "conservation_status": "Endangered"}]})
db["Animals"].find({ "common_name": "Lion" })
db["Animals"].find({ "physical_characteristics.length": {"$gt": 200 } })
db["Animals"].find({ "found_in_countries" : {"$regex": "Africa"} })
db["Animals"].find({ "common_name" : {"$regex": "^A"} })
db["Animals"].find({ $and: [{"diet": "Carnivore"}, {"physical_characteristics.weight": {"$lt": 50000}}]})
db["Animals"].find({ $and: [{"conservation_status" : "Vulnerable"}, {"habitat": "Desert"}] })
db["Animals"].find({ "common_name": {"$regex": "Tiger"} })